# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Audits

on:
  workflow_dispatch:
    branches:
      - 'master'
  schedule:
      # * is a special character in YAML so you have to quote this string
      - cron: '0 0 * * *'

jobs:
  Audits:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: \${{ runner.os }}-m2-\${{ hashFiles('**/pom.xml') }}
          restore-keys: \${{ runner.os }}-m2
      - name: Configure the job
        run: |
          rm -vf github.properties
          curl -o github.properties https://ghactions:${{ secrets.GH_PASSWD }}@evanchooly.com/private/files/github.properties
          mkdir -p ~/.m2
          curl -o ~/.m2/settings.xml https://ghactions:${{ secrets.GH_PASSWD }}@evanchooly.com/private/files/settings.xml
      - name: Build
        run: mvn -e -f audits/pom.xml test -DGITHUB_PROPERTIES=`pwd`/github.properties
